# Generated by Django 4.0.1 on 2022-01-27 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('level', models.CharField(choices=[('novice', 'Новичок'), ('novice+', 'Новичок+'), ('junior', 'Джуниор')], default='novice', max_length=255, verbose_name='Уровень')),
                ('tg_username', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Telegram')),
                ('discord_username', models.CharField(blank=True, max_length=255, verbose_name='Discord')),
                ('is_far_east', models.BooleanField(verbose_name='Ученик с ДВ')),
                ('time', models.TimeField(blank=True, verbose_name='Время созвона')),
            ],
        ),
    ]
