# Generated by Django 4.0.1 on 2022-01-27 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('tg_username', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Telegram')),
                ('time_from', models.TimeField(verbose_name='Работает с')),
                ('time_to', models.TimeField(verbose_name='Работает по')),
            ],
        ),
    ]
