# Generated by Django 4.0.1 on 2022-01-27 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0002_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время созвона'),
        ),
    ]
