# Generated by Django 4.0.1 on 2022-01-27 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0002_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время созвона'),
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(verbose_name='Время созвона')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='automation.manager', verbose_name='ПМ')),
                ('students', models.ManyToManyField(to='automation.Student', verbose_name='Студенты')),
            ],
        ),
    ]
