# Generated by Django 4.0.1 on 2022-01-27 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0003_alter_student_time_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название проекта')),
                ('groups', models.ManyToManyField(blank=True, to='automation.Group', verbose_name='Группы')),
            ],
        ),
    ]
