# Generated by Django 4.0.1 on 2022-01-28 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0003_alter_student_time_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название проекта')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(verbose_name='Время созвона')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='automation.manager', verbose_name='ПМ')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automation.project', verbose_name='Проект')),
                ('students', models.ManyToManyField(to='automation.Student', verbose_name='Студенты')),
            ],
        ),
    ]
