# Generated by Django 4.0.1 on 2022-01-28 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0004_project_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='LonelyStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automation.project', verbose_name='Проект')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automation.student', verbose_name='Студент')),
            ],
        ),
    ]
